name: minecraft_ltbl
main: team.imcc.ltbl.Main
version: 1.1
api-version: 1.14
author: FJYsmall
description: Let there be light!
commands:
  ltbl:
    description: lighter on/off switch.
    usage: /<command>
